# Generated by Django 3.2.9 on 2021-11-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_delete_mybox'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(related_name='like_users', to='movies.Movie'),
        ),
    ]
