# Generated by Django 3.2.9 on 2021-11-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_mybox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybox',
            old_name='movie',
            new_name='my_box_users',
        ),
    ]
