# Generated by Django 3.2.9 on 2021-11-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_movie_mybox_my_box_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybox',
            old_name='my_box_users',
            new_name='movies',
        ),
    ]
