# Generated by Django 3.2.9 on 2021-11-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_my_box_users_mybox_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mybox',
        ),
    ]
