# Generated by Django 3.2.9 on 2021-11-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
    ]
